[package]
name = "thetube"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bench-basic"
path = "benches/basic.rs"

[[bin]]
name = "publish-throughput"
path = "benches/publish_throughput.rs"

[[bin]]
name = "bench-e2e"
path = "benches/bench_e2e.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
crossbeam = "0.8"
dashmap = "6.1"
fastrand = "2"
futures = "0.3"
rocksdb = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
